# Generated by Django 3.2 on 2021-04-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receita',
        ),
    ]
