# Generated by Django 3.2 on 2021-04-27 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='mode_preparo',
            new_name='modo_preparo',
        ),
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 11, 0, 29, 399649)),
        ),
    ]
