# Generated by Django 3.2 on 2021-04-27 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0009_alter_receita_date_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='date_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 11, 39, 36, 120425)),
        ),
    ]
